version: "3.7"

services:
  project-zomboid:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SERVER_NAME: "Kappa-42"
      SERVER_PASSWORD: K@ppaT3st1nG!
      ADMIN_PASSWORD: "original-password"
    ports:
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16261:16261/udp"
      - "16262-16272:16262-16272"
      - "27015:27015"
    volumes:
      - ./server-data:/server-data